---
- name: Copy the RrabbitMQ Exporter systemd service file
  template:
    src: rabbitmq_exporter.service.j2
    dest: /etc/systemd/system/rabbitmq_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart rabbitmq_exporter
