---
- name: Create the rabbitmq_exporter group
  group:
    name: "{{ rabbitmq_exporter_system_group }}"
    state: present
    system: true
  when: rabbitmq_exporter_system_group != "root"

- name: Create the rabbitmq_exporter user
  user:
    name: "{{ rabbitmq_exporter_system_user }}"
    groups: "{{ rabbitmq_exporter_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
  when: rabbitmq_exporter_system_user != "root"

- name: Download rabbitmq_exporter binary
  become: false
  get_url:
    url: "https://github.com/kbudde/rabbitmq_exporter/releases/download/v{{ rabbitmq_exporter_version }}/rabbitmq_exporter-{{ rabbitmq_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp/rabbitmq_exporter-{{ rabbitmq_exporter_version }}.linux-amd64.tar.gz"
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  delegate_to: localhost
  check_mode: false

- name: Unpack rabbitmq_exporter binary
  become: false
  unarchive:
    src: "/tmp/rabbitmq_exporter-{{ rabbitmq_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp"
    creates: "/tmp/rabbitmq_exporter-{{ rabbitmq_exporter_version }}.linux-amd64/rabbitmq_exporter"
  delegate_to: localhost
  check_mode: false

- name: Create /usr/local/bin
  file:
    path: /usr/local/bin
    state: directory
    mode: 0755

- name: Propagate rabbitmq_exporter binaries
  copy:
    src: "/tmp/rabbitmq_exporter-{{ rabbitmq_exporter_version }}.linux-amd64/rabbitmq_exporter"
    dest: "/usr/local/bin/rabbitmq_exporter"
    mode: 0755
    owner: root
    group: root
  notify: restart rabbitmq_exporter
  when: not ansible_check_mode
