---
- import_tasks: preflight.yml
  tags:
    - rabbitmq_exporter_install
    - rabbitmq_exporter_configure
    - rabbitmq_exporter_run

- import_tasks: install.yml
  become: true
  tags:
    - rabbitmq_exporter_install

- import_tasks: configure.yml
  become: true
  tags:
    - rabbitmq_exporter_configure

- name: Ensure rabbitmq_exporter is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: rabbitmq_exporter
    enabled: true
    state: started
  tags:
    - rabbitmq_exporter_run
