---
- name: Assert usage of systemd as an init system
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd"

- name: Check if rabbitmq_exporter is installed
  stat:
    path: "/usr/local/bin/rabbitmq_exporter"
  register: __rabbitmq_exporter_is_installed
  tags:
    - rabbitmq_exporter_install
